server:
  port: 9999
spring:
  jackson:
    default-property-inclusion: non_null
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:test

  http:
    multipart:
      max-file-size: 5MB